ARG BUILDER_IMAGE=icr.io/ibm-dreadnought-prod-images/ubi9/python312-builder
ARG NODE_BUILDER_IMAGE=icr.io/ibm-dreadnought-prod-images/ubi9/nodejs20-builder

ARG DREADNOUGHT_PYTHON312_TAG=SET_VALID_TAG
ARG NODE_BUILDER_TAG=v9.6.49

FROM ${NODE_BUILDER_IMAGE}:${NODE_BUILDER_TAG} AS node-deps

RUN npm install -g @ivotoby/openapi-mcp-server

FROM ${BUILDER_IMAGE}:${DREADNOUGHT_PYTHON312_TAG} AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

RUN mkdir -p /.cache/uv /app && chmod -R 0777 /.cache /app

COPY pyproject.toml uv.lock ./

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-install-project --no-dev

COPY . /app

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-dev

RUN chmod -R 0777 /app

ENV PATH="/app/.venv/bin:$PATH"

CMD ["uv", "run", "src/mcp_composer_client/acp_server.py"]
