[project]
name = "mcp-composer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckduckgo-search>=8.0.1",
    "fastmcp==2.10.3",
    "requests==2.32.3",
    "httpx==0.28.1",
    "ibmcloudant==0.10.2",
    "ibm-cloud-sdk-core==3.23.0",
    "fastapi==0.115.12",
    "aiohttp==3.12.12",
    "beeai-framework==0.1.29",
    "dotenv>=0.9.9",
    "jsonschema>=4.24.0",
    "uncurl==0.0.11",
    "chromadb>=1.0.15",
    "acp-sdk==1.0.0",
    "ibm-secrets-manager-sdk==2.1.10",
    "pydantic==2.11.7",
    "pydantic-settings==2.10.1",
]

[dependency-groups]
dev = [
    "dirty-equals==0.9.0",
    "pylint>=3.3.7",
    "pytest==8.3.3",
    "pytest-asyncio==0.23.5",
    "pytest-cov==6.1.1",
    "pytest-flakefinder",
    "pytest-report==0.2.1",
    "pytest-timeout==2.4.0",
    "pytest-xdist==3.6.1",
    "ruff",
]


[tool.pyright]
include = ["src", "test"]
exclude = ["**/node_modules", "**/__pycache__", ".venv", ".git", "dist"]
venvPath = "."
venv = ".venv"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["mcp_composer"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = [
    "test",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
mcp-composer = "mcp_composer.utils.cli:main"
