[project]
name = "mcp-composer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckduckgo-search>=8.0.1",
    "fastmcp==2.10.3",
    "requests==2.32.4",
    "httpx==0.28.1",
    "ibmcloudant==0.10.2",
    "ibm-cloud-sdk-core==3.23.0",
    "fastapi==0.116.1",
    "aiohttp==3.12.14",
    "beeai-framework==0.1.29",
    "dotenv>=0.9.9",
    "jsonschema>=4.24.0",
    "uncurl==0.0.11",
    "chromadb>=1.0.15",
    "acp-sdk==1.0.0",
    "sentence-transformers>=5.0.0",
    "np>=1.0.2",
    "hnswlib>=0.8.0",
    "ollama>=0.5.1",
    "ibm-secrets-manager-sdk==2.1.10",
    "pydantic==2.11.7",
    "pydantic-settings==2.10.1",
    "hvac==2.3.0",
]

[dependency-groups]
dev = [
    "dirty-equals==0.9.0",
    "pylint>=3.3.7",
    "pytest==8.3.3",
    "pytest-asyncio==0.23.5",
    "pytest-cov==6.1.1",
    "pytest-flakefinder",
    "pytest-report==0.2.1",
    "pytest-timeout==2.4.0",
    "pytest-xdist==3.6.1",
    "ruff",
]


[tool.pyright]
include = ["src", "test"]
exclude = ["**/node_modules", "**/__pycache__", ".venv", ".git", "dist"]
venvPath = "."
venv = ".venv"


[tool.pylint.'MAIN']
# Example options:
ignore = ["venv", "migrations", "build"]
max-line-length = 120
disable = ["C0114", "C0115", "C0116"]  # Example: disables missing docstring warnings

[tool.pylint.messages_control]
# Enable/disable specific messages
disable = ["missing-docstring", "invalid-name"]


[tool.ruff]
line-length = 120
exclude = ["venv", "migrations", "build", "dist"]
select = ["E", "F", "W"]  # Which error codes to check
ignore = ["E501"]         # Example: ignore line length errors

[tool.ruff.lint]
ignore = ["E501", "F401"]
select = ["E", "F", "W"]


[tool.setuptools]
package-dir = {"" = "src"}
packages = ["mcp_composer", "mcp_composer.settings", 
            "mcp_composer.auth_handler", "mcp_composer.member_servers",
            "mcp_composer.utils", "mcp_composer.middleware",
            "mcp_composer.models", "mcp_composer.store",
            "mcp_composer.tools"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = [
    "test",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
mcp-composer = "mcp_composer.utils.cli:main"
